### ISSUE TITLE
assigning to inputs?

### ISSUE THREAD

**Issue by o-smirnov** [landmanbester/stimecipes#2]
@landmanbester I'm finding this pattern a bit questionable: https://github.com/landmanbester/stimecipes/blob/d822030fed4cc538767a8588d45e67d29d294d6c/pfbimage.yaml#L22

What are you trying to do here, set a default value for an aliased input? I'm thinking of disallowing assignments to inputs anyway, as there are corner cases where this causes weirdness. 

The correct pattern would be something like:

```yml
inputs:
  output-filename:
  default: '{current.basedir}/{current.imagename}'
  alias: ['*.output-filename']
```
